package io.bluetape4k.javers.commit

import io.bluetape4k.idgenerators.snowflake.Snowflake
import io.bluetape4k.idgenerators.snowflake.Snowflakers
import kotlinx.atomicfu.atomic
import kotlinx.atomicfu.locks.reentrantLock
import org.javers.core.commit.CommitId
import java.util.concurrent.ConcurrentHashMap
import java.util.function.Supplier
import kotlin.concurrent.withLock

/**
 * [CommitId] generator backed by the [Snowflake] algorithm.
 *
 * ## Behavior / Contract
 * - Each [get] call produces a unique [CommitId] with a Snowflake ID as majorId and minorId=0.
 * - The sequence number assigned to each generated [CommitId] is accessible via [getSeq].
 * - Calling [getSeq] with a [CommitId] that was never generated throws [NoSuchElementException].
 * - [get] is thread-safe via an internal lock.
 *
 * ```kotlin
 * val generator = SnowflakeCommitIdGenerator()
 * val commitId = generator.get()
 * val seq = generator.getSeq(commitId)
 * // seq == 1
 * ```
 *
 * @property snowflake [Snowflake] instance used for ID generation
 */
class SnowflakeCommitIdGenerator(
    private val snowflake: Snowflake = Snowflakers.Default,
): Supplier<CommitId> {

    private val commits = ConcurrentHashMap<CommitId, Int>()
    private val counter = atomic(0)
    private val lock = reentrantLock()

    /**
     * Returns the sequence number assigned to [commitId].
     *
     * @throws NoSuchElementException if [commitId] was never generated by this instance
     */
    fun getSeq(commitId: CommitId): Int =
        commits[commitId] ?: throw NoSuchElementException("Not found commitId [$commitId]")

    override fun get(): CommitId = lock.withLock {
        counter.incrementAndGet()
        val next = CommitId(nextId(), 0)
        commits[next] = counter.value
        next
    }

    private fun nextId(): Long = snowflake.nextId()
}
