plugins {
    alias(libs.plugins.kotlin.spring)
}

dependencies {
    implementation(platform("org.springframework.boot:spring-boot-dependencies:${bt4k.versions.spring.boot4.get()}"))
    testImplementation(platform("org.springframework.boot:spring-boot-dependencies:${bt4k.versions.spring.boot4.get()}"))
    compileOnly(platform(libs.exposed.bom))
    testImplementation(platform(libs.exposed.bom))

    compileOnly(libs.javers.core)
    compileOnly(libs.bluetape4k.core)
    compileOnly(project(":javers-core"))
    compileOnly(project(":javers-exposed"))
    compileOnly(project(":javers-persistence-redis"))
    compileOnly(project(":javers-persistence-kafka"))

    compileOnly(libs.exposed.jdbc)
    compileOnly(libs.lettuce.core)
    compileOnly(libs.redisson)
    compileOnly(libs.spring.kafka)
    compileOnly(libs.kafka.clients)
    compileOnly(libs.fory.kotlin)
    compileOnly(libs.lz4.java)
    compileOnly("org.springframework.boot:spring-boot")
    compileOnly("org.springframework.boot:spring-boot-autoconfigure")
    compileOnly("org.springframework:spring-context")

    testImplementation(project(":javers-core"))
    testImplementation(project(":javers-exposed"))
    testImplementation(project(":javers-persistence-redis"))
    testImplementation(project(":javers-persistence-kafka"))
    testImplementation(libs.exposed.jdbc)
    testImplementation(libs.bluetape4k.core)
    testImplementation(libs.bluetape4k.junit5)
    testImplementation(libs.bluetape4k.lettuce)
    testImplementation(libs.bluetape4k.redisson)
    testImplementation(libs.bluetape4k.kafka)
    testImplementation(libs.lettuce.core)
    testImplementation(libs.redisson)
    testImplementation(libs.spring.kafka)
    testImplementation(libs.kafka.clients)
    testImplementation(libs.fory.kotlin)
    testImplementation(libs.lz4.java)
    testImplementation("org.springframework.boot:spring-boot-test")
    testImplementation("org.springframework.boot:spring-boot-autoconfigure")
    testImplementation("org.springframework:spring-context")
    testImplementation("org.assertj:assertj-core")
    testRuntimeOnly(libs.h2)
}
