plugins {
    alias(bt4k.plugins.kotlin.spring)
}

dependencies {
    implementation(platform("org.springframework.boot:spring-boot-dependencies:${bt4k.versions.spring.boot4.get()}"))
    testImplementation(platform("org.springframework.boot:spring-boot-dependencies:${bt4k.versions.spring.boot4.get()}"))
    compileOnly(platform(bt4k.exposed.bom))
    testImplementation(platform(bt4k.exposed.bom))

    compileOnly(libs.javers.core)
    compileOnly(bt4k.bluetape4k.core)
    compileOnly(project(":javers-core"))
    compileOnly(project(":javers-exposed"))
    compileOnly(project(":javers-persistence-redis"))
    compileOnly(project(":javers-persistence-kafka"))

    compileOnly(bt4k.exposed.jdbc)
    compileOnly(libs.lettuce.core)
    compileOnly(bt4k.redisson)
    compileOnly(libs.spring.kafka)
    compileOnly(libs.kafka.clients)
    compileOnly(bt4k.fory.kotlin)
    compileOnly(libs.lz4.java)
    compileOnly("org.springframework.boot:spring-boot")
    compileOnly("org.springframework.boot:spring-boot-autoconfigure")
    compileOnly("org.springframework:spring-context")

    testImplementation(project(":javers-core"))
    testImplementation(project(":javers-exposed"))
    testImplementation(project(":javers-persistence-redis"))
    testImplementation(project(":javers-persistence-kafka"))
    testImplementation(bt4k.exposed.jdbc)
    testImplementation(bt4k.bluetape4k.core)
    testImplementation(bt4k.bluetape4k.junit5)
    testImplementation(bt4k.bluetape4k.lettuce)
    testImplementation(bt4k.bluetape4k.redisson)
    testImplementation(bt4k.bluetape4k.kafka)
    testImplementation(libs.lettuce.core)
    testImplementation(bt4k.redisson)
    testImplementation(libs.spring.kafka)
    testImplementation(libs.kafka.clients)
    testImplementation(bt4k.fory.kotlin)
    testImplementation(libs.lz4.java)
    testImplementation("org.springframework.boot:spring-boot-test")
    testImplementation("org.springframework.boot:spring-boot-autoconfigure")
    testImplementation("org.springframework.boot:spring-boot-kafka")
    testImplementation("org.springframework:spring-context")
    // ApplicationContextRunner의 assertable context API에 필요하며 assertion은 bluetape4k 범위에서만 사용합니다.
    testImplementation("org.assertj:assertj-core")
    testRuntimeOnly(libs.h2)
}
